# Generated by Django 5.0.4 on 2024-06-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_remove_nutritionists_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionists',
            name='email',
            field=models.EmailField(default='babycare@gmail.com', max_length=150),
        ),
    ]
